"""empty message

Revision ID: bc81cc230269
Revises: fc51fcfadbb4
Create Date: 2022-12-07 09:28:04.865090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc81cc230269'
down_revision = 'fc51fcfadbb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_lesson_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_parent_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['education_system_grade.id'], ),
    sa.ForeignKeyConstraint(['lesson_parent_id'], ['lesson_lesson_parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_lesson')
    op.drop_table('lesson_lesson_parent')
    # ### end Alembic commands ###
