"""empty message

Revision ID: 476ecb67dc2e
Revises: 89edf35deefd
Create Date: 2022-12-26 09:02:58.382289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476ecb67dc2e'
down_revision = '89edf35deefd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_question', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_question', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
