"""empty message

Revision ID: 62e8d2d7b59a
Revises: 485c173eb4c5
Create Date: 2022-12-17 10:07:13.522324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62e8d2d7b59a'
down_revision = '485c173eb4c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    exam_lesson_type = postgresql.ENUM('GENERAL', 'SPECIAL', name='examlessontype')
    exam_lesson_type.create(op.get_bind())

    op.add_column('exam_lesson_exam',
                  sa.Column('type', sa.Enum('GENERAL', 'SPECIAL', name='examlessontype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_lesson_exam', 'type')

    exam_lesson_type = postgresql.ENUM('GENERAL', 'SPECIAL', name='examlessontype')
    exam_lesson_type.drop(op.get_bind())
    # ### end Alembic commands ###
