"""empty message

Revision ID: 485c173eb4c5
Revises: 7f364c226f42
Create Date: 2022-12-17 10:06:49.697523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485c173eb4c5'
down_revision = '7f364c226f42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_lesson_exam', sa.Column('coefficient', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_lesson_exam', 'coefficient')
    # ### end Alembic commands ###
