"""empty message

Revision ID: b3bdfd727e53
Revises: 
Create Date: 2022-12-11 10:26:54.574515

"""
from alembic import op
import sqlalchemy as sa

from app.models import Grade

# revision identifiers, used by Alembic.
revision = 'b3bdfd727e53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_system_grade',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('base_grade', sa.Enum('ELEMENTARY', 'MIDDLE_ONE', 'MIDDLE_TWO', name='basegrade'),
                              nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['education_system_grade.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('lesson_lesson',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('association_lesson_grade',
                    sa.Column('lesson_id', sa.Integer(), nullable=False),
                    sa.Column('grade_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['grade_id'], ['education_system_grade.id'], ),
                    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_lesson.id'], ),
                    sa.PrimaryKeyConstraint('lesson_id', 'grade_id')
                    )
    op.create_table('lesson_topic',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('lesson_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_lesson.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('question_question',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question_text', sa.String(), nullable=False),
                    sa.Column('answer_text', sa.String(), nullable=False),
                    sa.Column('type', sa.Enum('TEST', 'DESCRIPTIVE', name='typequestion'), nullable=False),
                    sa.Column('lesson_id', sa.Integer(), nullable=False),
                    sa.Column('topic_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_lesson.id'], ),
                    sa.ForeignKeyConstraint(['topic_id'], ['lesson_topic.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    seed()
    # ### end Alembic commands ###


def seed():
    op.bulk_insert(Grade.__table__,
                   [
                       {'id': 10, 'title': 'اول', 'base_grade': 'ELEMENTARY'},
                       {'id': 11, 'title': 'دوم', 'base_grade': 'ELEMENTARY'},
                       {'id': 12, 'title': 'سوم', 'base_grade': 'ELEMENTARY'},
                       {'id': 13, 'title': 'چهارم', 'base_grade': 'ELEMENTARY'},
                       {'id': 14, 'title': 'پنجم', 'base_grade': 'ELEMENTARY'},
                       {'id': 15, 'title': 'ششم', 'base_grade': 'ELEMENTARY'},

                       {'id': 16, 'title': 'هفتم', 'base_grade': 'MIDDLE_ONE'},
                       {'id': 17, 'title': 'هشتم', 'base_grade': 'MIDDLE_ONE'},
                       {'id': 18, 'title': 'نهم', 'base_grade': 'MIDDLE_ONE'},

                       {'id': 30, 'title': 'دهم', 'base_grade': 'MIDDLE_TWO'},
                       {'id': 19, 'title': 'ریاضی و فیزیک', 'base_grade': 'MIDDLE_TWO', 'parent_id': 30},
                       {'id': 20, 'title': 'علوم تجربی', 'base_grade': 'MIDDLE_TWO', 'parent_id': 30},
                       {'id': 21, 'title': 'علوم انسانی', 'base_grade': 'MIDDLE_TWO', 'parent_id': 30},

                       {'id': 31, 'title': 'یازدهم', 'base_grade': 'MIDDLE_TWO'},
                       {'id': 22, 'title': 'ریاضی و فیزیک', 'base_grade': 'MIDDLE_TWO', 'parent_id': 31},
                       {'id': 23, 'title': 'علوم تجربی', 'base_grade': 'MIDDLE_TWO', 'parent_id': 31},
                       {'id': 24, 'title': 'علوم انسانی', 'base_grade': 'MIDDLE_TWO', 'parent_id': 31},

                       {'id': 32, 'title': 'دوازدهم', 'base_grade': 'MIDDLE_TWO'},
                       {'id': 25, 'title': 'ریاضی و فیزیک', 'base_grade': 'MIDDLE_TWO', 'parent_id': 32},
                       {'id': 26, 'title': 'علوم تجربی', 'base_grade': 'MIDDLE_TWO', 'parent_id': 32},
                       {'id': 27, 'title': 'علوم انسانی', 'base_grade': 'MIDDLE_TWO', 'parent_id': 32},
                   ], multiinsert=False
                   )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_question')
    op.drop_table('lesson_topic')
    op.drop_table('association_lesson_grade')
    op.drop_table('lesson_lesson')
    op.drop_table('education_system_grade')
    # ### end Alembic commands ###
