"""empty message

Revision ID: b3619543e46d
Revises: bc81cc230269
Create Date: 2022-12-10 09:07:26.780886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3619543e46d'
down_revision = 'bc81cc230269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_association_lesson_target',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_lesson.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['lesson_target.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'target_id')
    )
    op.create_table('lesson_association_lesson_topic',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_lesson.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['lesson_topic.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_association_lesson_topic')
    op.drop_table('lesson_association_lesson_target')
    op.drop_table('lesson_topic')
    op.drop_table('lesson_target')
    # ### end Alembic commands ###
