"""empty message

Revision ID: 5511d11884d5
Revises: 4d7cdf462144
Create Date: 2022-12-17 13:54:28.922657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5511d11884d5'
down_revision = '4d7cdf462144'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    type_question = postgresql.ENUM('TEST', 'DESCRIPTIVE', name="typequestion", create_type=False)
    type_question.create(op.get_bind(), checkfirst=True)

    op.create_table('exam_question',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('exam_lesson_id', sa.Integer(), nullable=False),
                    sa.Column('question_text', sa.String(), nullable=False),
                    sa.Column('answer_text', sa.String(), nullable=True),
                    sa.Column('type', type_question, nullable=False),
                    sa.Column('topic_id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.Column('question_number', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['exam_lesson_id'], ['exam_lesson_exam.id'], ),
                    sa.ForeignKeyConstraint(['question_id'], ['question_question.id'], ),
                    sa.ForeignKeyConstraint(['topic_id'], ['lesson_topic.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_question')

    type_question = postgresql.ENUM('TEST', 'DESCRIPTIVE', name="typequestion", create_type=False)
    type_question.drop(op.get_bind())
    # ### end Alembic commands ###
