"""empty message

Revision ID: e61c569f5a08
Revises: 80d9b91888e7
Create Date: 2022-12-24 16:11:14.225094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61c569f5a08'
down_revision = '80d9b91888e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_system_class_room', sa.Column('token', sa.String(), nullable=False))
    op.add_column('education_system_school', sa.Column('token', sa.String(), nullable=False))
    op.add_column('user_agency', sa.Column('token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_agency', 'token')
    op.drop_column('education_system_school', 'token')
    op.drop_column('education_system_class_room', 'token')
    # ### end Alembic commands ###
