"""empty message

Revision ID: 7f364c226f42
Revises: cb2aea34384b
Create Date: 2022-12-15 10:44:40.075282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f364c226f42'
down_revision = 'cb2aea34384b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TEST', 'DESCRIPTIVE', name='examtype'), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['education_system_grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_lesson_exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_exam.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_lesson_exam')
    op.drop_table('exam_exam')
    # ### end Alembic commands ###
