"""empty message

Revision ID: 4d7cdf462144
Revises: 34ce6a6c7bac
Create Date: 2022-12-17 10:48:52.065408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7cdf462144'
down_revision = '34ce6a6c7bac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_lesson_exam', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_lesson_exam', 'duration')
    # ### end Alembic commands ###
