"""empty message

Revision ID: 1d0f30f1bced
Revises: e61c569f5a08
Create Date: 2022-12-25 10:27:59.867509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0f30f1bced'
down_revision = 'e61c569f5a08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_user_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_user_id', sa.Integer(), nullable=False),
    sa.Column('exam_question_id', sa.Integer(), nullable=False),
    sa.Column('answer_image', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exam_question_id'], ['exam_question.id'], ),
    sa.ForeignKeyConstraint(['exam_user_id'], ['exam_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_user_question')
    # ### end Alembic commands ###
