"""empty message

Revision ID: 34ce6a6c7bac
Revises: 62e8d2d7b59a
Create Date: 2022-12-17 10:39:38.037433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34ce6a6c7bac'
down_revision = '62e8d2d7b59a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    question_paper_type = postgresql.ENUM('FULL', 'LESSON_SEPARATE', 'LESSON_TYPE_SEPARATE', name='questionpapertype')
    question_paper_type.create(op.get_bind())

    op.add_column('exam_exam', sa.Column('question_paper_type',
                                         sa.Enum('FULL', 'LESSON_SEPARATE', 'LESSON_TYPE_SEPARATE',
                                                 name='questionpapertype'), nullable=False, server_default='FULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_exam', 'question_paper_type')

    question_paper_type = postgresql.ENUM('FULL', 'LESSON_SEPARATE', 'LESSON_TYPE_SEPARATE', name='questionpapertype')
    question_paper_type.drop(op.get_bind())
    # ### end Alembic commands ###
