"""empty message

Revision ID: ae51781af4dc
Revises: 5511d11884d5
Create Date: 2022-12-21 08:36:05.910346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae51781af4dc'
down_revision = '5511d11884d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_question', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_question', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
