"""empty message

Revision ID: 3b8dd1516e74
Revises: 81b571390ea9
Create Date: 2023-01-12 10:53:01.561399

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3b8dd1516e74'
down_revision = '81b571390ea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('is_staff', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', 'is_staff')
    # ### end Alembic commands ###
