"""empty message

Revision ID: 0d6e047ba514
Revises: 0da95cfbe4b3
Create Date: 2023-02-26 09:56:31.350460

"""
import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0d6e047ba514'
down_revision = '0da95cfbe4b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_user',
                  sa.Column('created_at', sa.DateTime(), server_default=sa.text(f"'{datetime.datetime.utcnow().isoformat()}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_user', 'created_at')
    # ### end Alembic commands ###
