"""empty message

Revision ID: 45843f36bee1
Revises: 4c61f8b85e61
Create Date: 2023-01-12 11:44:38.763180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45843f36bee1'
down_revision = '4c61f8b85e61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_user', 'grade_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_user', 'agency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_user', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_user', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_user', 'agency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_user', 'grade_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
