"""empty message

Revision ID: 81b571390ea9
Revises: 0acb6dfc7929
Create Date: 2023-01-03 08:56:58.785039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b571390ea9'
down_revision = '0acb6dfc7929'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_user_score', 'score_ideal_percent')
    op.drop_column('exam_user_score', 'balance')
    op.drop_column('exam_user_score', 'score_ideal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_user_score', sa.Column('score_ideal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('exam_user_score', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('exam_user_score', sa.Column('score_ideal_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
