"""empty message

Revision ID: 0da95cfbe4b3
Revises: 45843f36bee1
Create Date: 2023-01-12 13:16:27.836915

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0da95cfbe4b3'
down_revision = '45843f36bee1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='True'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', 'is_active')
    # ### end Alembic commands ###
