"""empty message

Revision ID: 4c61f8b85e61
Revises: 3b8dd1516e74
Create Date: 2023-01-12 11:34:01.068621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c61f8b85e61'
down_revision = '3b8dd1516e74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_user', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_user', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
