"""empty message

Revision ID: 9b80d99db10e
Revises: 332e854f4134
Create Date: 2023-01-02 16:35:58.022020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b80d99db10e'
down_revision = '332e854f4134'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_user_score', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exam_user_score', 'exam_status', ['status_id'], ['id'])
    op.drop_column('exam_user_score', 'rank_class_room')
    op.drop_column('exam_user_score', 'rank_school')
    op.drop_column('exam_user_score', 'rank_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_user_score', sa.Column('rank_total', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exam_user_score', sa.Column('rank_school', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exam_user_score', sa.Column('rank_class_room', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_user_score', type_='foreignkey')
    op.drop_column('exam_user_score', 'status_id')
    # ### end Alembic commands ###
