"""empty message

Revision ID: 332e854f4134
Revises: ac1e7b711ef6
Create Date: 2023-01-02 14:47:19.746907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332e854f4134'
down_revision = 'ac1e7b711ef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CLASS_ROOM', 'SCHOOL', 'TOTAL', name='examstatustype'), nullable=False),
    sa.Column('start_percent', sa.Float(), nullable=False),
    sa.Column('end_percent', sa.Float(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_user_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LESSON', 'GENERAL', 'SPECIAL', 'TOTAL', name='examscoretype'), nullable=False),
    sa.Column('exam_lesson_id', sa.Integer(), nullable=True),
    sa.Column('exam_user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False),
    sa.Column('score_ideal', sa.Float(), nullable=False),
    sa.Column('score_ideal_percent', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('rank_class_room', sa.Integer(), nullable=False),
    sa.Column('rank_school', sa.Integer(), nullable=False),
    sa.Column('rank_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_lesson_id'], ['exam_lesson_exam.id'], ),
    sa.ForeignKeyConstraint(['exam_user_id'], ['exam_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_user_score')
    op.drop_table('exam_status')
    # ### end Alembic commands ###
